###############
## 
####

GPU: [3]

VERBOSE: True

MODEL:
  MODE: 'Demoire'
  SESSION: 'TIDNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 10
  NUM_EPOCHS: 50
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-4
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: false
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './Datasets/train'       # path to training data
  VAL_DIR: './Datasets/validation' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
